Ningzhi xu
1thing-org/1thing-crawler pull request #4
Opened 2022-01-24 00:15 UTC by SunnyStardust

1. python testConn.py -add text.txt
Add the incident read from text.txt to the database
2. python testConn.py -get
Get all incidents from the database

[.txt](https://github.com/1thing-org/1thing-crawler/files/7921775/default.txt)

Change the name of "default.txt" to ".env" to run the service.

2022-01-24 00:18 UTC, qz267 requested changes
All LGTM, would you mind add some documentation to README.md to mention how to use the code?

2022-01-24 00:31 UTC, SunnyStardust commented
> All LGTM, would you mind add some documentation to README.md to mention how to use the code?

README.md updated

2022-01-25 02:36 UTC, qz267 commented on README.md
> +3. Get all incidents from the database: python testConn.py -get
missing item `2`?

2022-01-25 02:37 UTC, qz267 requested changes
Missing item `2`?

2022-01-25 04:36 UTC, qz267 approved these changes

2022-01-25 04:36 UTC, merged